### PR TITLE
Predict changes

### PR DESCRIPTION
**Pull request by jspeed-meyers**
Here are the major changes associated with this PR:
1. **New test data** - Added new test data with only three unique roles and only two unique roles in TOTAL. The old code would throw an error if there were only two roles or three roles present. I have not added a test data for only one role present in the model--it just doesn't make sense to have only one role in a model.
2. **New unit test** - Added a unit test to check that the code works for only two or three unique roles.
3. **Refactoring predict** - Split predict() into two functions to make reading and maintaining easier
4. **Output logic** - As part of refactoring predict, made some small changes that added logic how many roles and associated probabilities to output.

Note: there was some minor linting too.

### CODE REVIEW

**Comment by jspeed-meyers** [comment]
@cglewis, there seems to be a test failing related to the featurizer. It's failing locally too. I'm not sure what is happening.

**Comment by cglewis** [comment]
@jspeed-meyers the test in the unit tests that's failing the `test_predict` which is related to this PR. As mentioned before the `make` tests can be ignored for the moment, but the unit tests under `test` need to pass.

**Comment by jspeed-meyers** [comment]
All my tests are passing locally. When I push to this branch, it tells me that "everything is up to date." I am going to rerun the test suite on travis. I'll work on this again on Monday morning.

**Comment by jspeed-meyers** [comment]
Looks like it is sklearn_json-related. I'll dig into it.

**Comment by cglewis** [comment]
@jspeed-meyers @anarkiwi was able to track down the cause to the test failures and pushed up a fix with #621. If you pull from upstream into your PRs they should pass again.

**Comment by jspeed-meyers** [comment]
I pulled from upstream, ran tests locally (they passed), and pushed this up. We'll see! Thanks @cglewis and @anarkiwi

**Pull request merged**
