### PR TITLE
Unknown role functionality

### PR DESCRIPTION
**Pull request by jspeed-meyers**
I added logic to make networkML return a top role and not just a list of the top roles. The current code is intended to make the top role unknown if the probability is less than the specified threshold. I wrote in .5 as the default threshold--we can always change that.

### CODE REVIEW

**Comment by jspeed-meyers** [comment]
Hmmm, there seems to be a conflicting file. @cglewis, what do I need to do here?

**Comment by jspeed-meyers** [comment]
I used the in-GitHub merge editor. We'll see how that went.

**Comment by cglewis** [comment]
@jspeed-meyers looks like your merge undid some of my linting from #623 - codacy identified the trailing whitespace if you can fix that, otherwise looks pretty good.

**Comment by cglewis** [comment]
I'll merge and fix the whitespace. Thanks!

**Comment by jspeed-meyers** [comment]
Apologies on editing your linting. Oops.

**Pull request merged**
