### PR TITLE
edit host_footprint file, especially predict function

### PR DESCRIPTION
**Pull request by jspeed-meyers**
This PR will not pass. **Do not merge.**

Here's the problem: We need to add a new combined.csv file. This PR adds in [k-fold cross validation](https://scikit-learn.org/stable/modules/cross_validation.html). Consequently, the training data for the unit-tests must have a new property: there must be at 5 examples of each functional role in the training data. The number five is important because the PR calls for 5-fold cross validation. The current combined.csv does not have this property.

This means that either Josh or I need to generate a new combined.csv (for the host footprint) that has at least five examples of each class included in the file. I assert that after adding such a new test dataset, the tests will pass. 

One small caveat: there must be at least four different classes in the test dataset, otherwise the tests will still fail. We can discuss that aspect too. Perhaps this is a bug that requires fixing.

### CODE REVIEW

**Comment by cglewis** [comment]
Can we make `cv=5` a parameter that gets passed and that has a default of 5, but then in tests can be a lower value?

**Comment by jspeed-meyers** [comment]
That is not only possible but a great idea. Let me work on this and I'll submit something later. We might still have to change the testing dataset (combined.csv) but the change would be smaller. I'll report back on that too.

**Comment by jspeed-meyers** [comment]
I made an argument in the train function named k_folds that can be used to provide a value to the cv argument, but upon looking at this closer, I can't figure out how to use the current testing code to pass this argument. I'll need your help, @cglewis.

**Comment by jspeed-meyers** [comment]
I put a kfolds arguments into argparse and I can make the tests pass on my computer with my new test data. I'm not sure if the arguments will pass with the old test data. I doubt it. I'll check back later this afternoon.

**Comment by cglewis** [comment]
@jspeed-meyers you still need to update the tests to change the default of `kfolds` to not be 5.

**Comment by jspeed-meyers** [comment]
Thanks for pointing that out. I still haven't changed the testing data. We'll see if the tests pass without a change in the combined.csv data. Adding in cross validation and setting cv=2 means that there must be at least two examples for each type of functional role present in the combined.csv. To be explicit, we NOT need examples of all functional roles. We simply need two examples for each role that is present.

**Comment by cglewis** [comment]
@jspeed-meyers yup, looks like you're right, the test data also needs to be updated.

**Comment by jspeed-meyers** [comment]
Fingers crossed! I replaced the test data in combined.csv with a new version that has these properties: all functional role classes present (there are four) have at least two observations. I simply made a copy of each pre-existing row and also changed one feature value. This is really mock data. 

There is one more change I am considering. I think it might be best to get rid of the string_feature_check() function and functionality--I think Josh's code already does checks about feature integrity and I don't think this code and function is necessary.

**Comment by jspeed-meyers** [comment]
Fail! @cglewis, can you please help me replicate this error on my local machine? It doesn't seem to involve the pytest test suite but the make file. I need some guidance.

**Comment by cglewis** [comment]
@jspeed-meyers I'm re-running the tests. you can reproduce that check locally with `make test` which passes locally for me, so could have been a glitch in CI.  As for the `string_feature_check()` I think we should keep it, as it helps validate incoming data which could come from anywhere, not just necessarily stage2 output.

**Comment by jspeed-meyers** [comment]
Keeping ```string_feature_check()``` is fine with me. Thanks for consulting. And I'll go run that ```make test``` command now locally.

**Comment by jspeed-meyers** [comment]
I added the revised test data. @cglewis, three workflow questions for you: 1) Should I have merged the upstream into this fork before I started any work at all on this PR? See ```7b12d63```. I only pulled the upstream into my local machine and was just using the fork as a waypoint, not keeping it up to date. I sense that my method is NOT how I should operate. 2) When I tried to push the new revised data (thank you again), git wanted me to pull down the changes that had happened on my fork first, that merge. And so there was yet another addition of those merged changes. See ```11af7e3```This seems off. Should I have done something differently? And 3) Should I make local branches before I do PR's so that a given PR is simply a branch? I didn't do that here, but could in the future. Thanks for the help.

**Comment by cglewis** [comment]
@jspeed-meyers there are a number of different ways to use `git`. I'd pick a workflow that works for you. Generally speaking, I think best practice is to have a specific branch for your PR that is separate from `master`. This lets you use your `master` branch on your fork to sync up with the upstream `master` branch so that when you cut new branches for various PRs (which could be open simultaneously) you can cut them from `master` and know it's clean and not have changes or commits from other PRs that might require changes or not get merged for one reason or another.

As for syncing up your PR with upstream master, that is generally expected, so that the tests running against your fork will pass before merging and after merging without surprises. Some projects/branches enforce it. However, when you sync can be variable, because the upstream can change and merge other PRs before yours, so you might have to sync up your branch on your PR several times before it get merged in.

Any time you merge in changes to your fork/branch through GitHub, you'll need to pull those changes into your local clone, otherwise your commit history won't match and `git` will complain. If you make commits to your local clone before pulling down the latest commits that changed on GitHub, it will make a `merge branch` commit to rectify the differing commit histories.

**Pull request merged**
